### ISSUE TITLE
Build failure on GHC 7.8

### ISSUE THREAD

**Issue by snoyberg** [mgajda/json-autotype#5]
```
Data/Aeson/AutoType/Format.hs:169:53:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<.>’ (imported from Control.Lens),
      ‘<&>’ (imported from Control.Lens)

Data/Aeson/AutoType/Format.hs:172:87:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<.>’ (imported from Control.Lens),
      ‘<&>’ (imported from Control.Lens)
[9 of 9] Compiling Data.Aeson.AutoType.Plugin.Subtype ( Data/Aeson/AutoType/Plugin/Subtype.hs, dist/build/Data/Aeson/AutoType/Plugin/Subtype.o )
```

**Comment by mgajda** [comment]
Thanks, should be fixed as of 0.4.
See: https://travis-ci.org/mgajda/json-autotype/jobs/57131543

**Comment by snoyberg** [comment]
I'm reproducing this on GHC 7.8.4.

**Comment by snoyberg** [comment]
To clarify: with json-autotype-0.4 from Hackage.

**Comment by mgajda** [comment]
Ok, will fix it today.

**Comment by mgajda** [comment]
Ok, made a wrong upload.

**Comment by mgajda** [comment]
Now builds correctly with both `7.8` and `7.6`.
